feature: добавлены интерфейсы FilmStorage и UserStorage, с их реализа…
TrapeznikovDanila/java-filmorate pull request #2
Opened 2022-08-16 17:19 UTC by TrapeznikovDanila

feature: добавлены интерфейсы FilmStorage и UserStorage, с их реализациями в классах InMemoryFilmStorage и InMemoryUserStorage, перенесена реализация старой логики. Добавлены классы FilmService и UserService с логикой добавления пользователей в друзья, добавления лайков к фильмам. Добавлен класс-обработчик ошибок ErrorHandler

2022-08-17 06:54 UTC, sergeymamonov requested changes

2022-08-17 06:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    void isValid(Film film);
Это интерфейс работы с хранилищем. Хранилище не может валидировать объекты. Оно может хранить, удалять, обновлять. Аналогично для второго интерфейса.

2022-08-17 06:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    protected HashMap<Long, Film> films = new HashMap<>();
Лучше интерфейс использовать Map<...

2022-08-17 06:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
Можно добавить логирование в каждый метод.

2022-08-17 06:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    }
Еще может возникать ошибка конфликта 409.

2022-08-17 06:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        isValid(film);
Этой валидации не место в хранилище. Перенесите в сервис. Здесь можно проверить, что после сервиса пришли корректные данные. А именно id, который добавляется в сервисе.

2022-08-17 06:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private int id = 0;
Готовить объекты (давать им id) нужно в сервисе.

2022-08-17 06:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        id++;
Можно так не писать в отдельной строке. А сделать это в сеттере .setId(id++). Экономится одна строчка и код становится более компактным.

2022-08-17 06:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
А почему id - это long, а здесь Long?
И duration - это int, а rate - это Integer?

2022-08-17 06:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void isFilmInMemory(long id) {
Если методы используются только в этом классе, то лучше их сделать private.

2022-08-17 06:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Long i : getUserById(id).getFriends()) {
Лучше выбирать более емкие по смыслу названия переменных, чем i, y. Такие названия переменных можно использовать только для циклов, где i это счетчик. И то, если несколько вложенных циклов, то уже лучше подумать о других названиях переменных. Здесь лучше давать информативные названия переменных, тем более, что за ними скрывается смысл.

2022-08-17 06:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return film;
А если попытаться сохранить фильм, который уже сохранен? Нужно ли кинуть ошибку конфликта в таком случае?

2022-08-17 14:02 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    void isValid(Film film);
Исправлено: созданы 2 отдельных класса для валидации

2022-08-17 14:04 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    protected HashMap<Long, Film> films = new HashMap<>();
Исправлено

2022-08-17 14:06 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
Добавлено

2022-08-17 14:08 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        isValid(film);
Исправлено

2022-08-17 14:13 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        id++;
Не исправлено. Такая запись не меняет общий счетчик id в хранилище

2022-08-17 14:19 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
Частично исправлено. Из каких-то прошлых замечаний к прошлым проектам помню, что лучше стараться не использовать класс-обертки, где не нужно, а в сет не запихнуть long, поэтому было так. rate Integer, потому что с int компаратор в FilmService getMostPopularFilms почему-то не работает

2022-08-17 14:19 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void isFilmInMemory(long id) {
Исправлено

2022-08-17 14:21 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Long i : getUserById(id).getFriends()) {
Исправлено. Не смог ничего лучше придумать, чем firstFriendFriendsId и secondFriendFriendsId

2022-08-17 14:26 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return film;
Исправлено

2022-08-17 14:26 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    }
Исправлено

2022-08-18 11:48 UTC, sergeymamonov requested changes
Замечания устранены не полностью.

2022-08-18 11:48 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.warn(e.getMessage());
А если приложение будет запущено с уровнем логирования error? С таким уровнем могут запустить в продакшене. Будет ли тогда видно в логах такое сообщение?

2022-08-18 11:48 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        id++;
Не очень понимаю ответ. Может быть ожидаете, что сразу будет изменено значение id? Есть разница между ++id и id++. В первом случае изменение произойдет до использования к id, а во втором случае - после.
То есть чтобы замена была идентичной нужно написать .set(++id).
Посмотрите постфиксная и префиксная форма. Либо, если я не понял ответа, поясните.

2022-08-18 11:48 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
При записи long или другого примитивного типа в коллекцию (множество, например) происходит автоупаковка, поэтому ошибки не возникнет.
"rate Integer, потому что с int компаратор в FilmService getMostPopularFilms" - посмотреть реализацию компаратора, посмотреть в деббаге. Если возникнут вопросы, спрашивайте

2022-08-18 11:48 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilmStorage().addFilm(film);
Нам нужно вызвать нужный метод сервиса.
В сервисе сделать нужную работу (провалидировать, присвоить id) и сохранить в стораже.

Сейчас эти действия разбросаны по разным пакетам: здесь валидация, id присваивается в стораже.

Когда приложение становится промышленного масштаба, то в нем много разных интеграций, слоев. Например интеграция с кафка, пульсаром, постгресом и так далее. И если в каждом модуле будет по чуть-чуть логики, то в какой-то момент будет на нейти где что. Поэтому вся логика работы с объектом должна быть в одном месте. В данном случае это сервис.

2022-08-18 15:13 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private int id = 0;
Исправлено

2022-08-18 15:14 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        id++;
Исправлено. Спасибо, разобрался

2022-08-18 15:22 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
Исправлено. Разобрался, в чем была проблема - компаратор - дженерик. Поэтому в FilmService getMostPopularFilms привел к Integer

2022-08-18 15:27 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.warn(e.getMessage());
Исправил. Думал, что подобные ошибки не важны для логирования - невалидные данные часто ведь могут отправлять пользователи, главное - сообщить им

2022-08-18 15:27 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilmStorage().addFilm(film);
Исправлено

2022-08-19 15:00 UTC, sergeymamonov approved these changes
Даны некоторые замечания, которые можно применить и к фильмам, и к пользователям.

2022-08-19 15:00 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void isValid(Film film) {
Обычно, если метод начинается с is..., то он возвращает логический тип. А здесь метод делает валидацию. Поэтому лучше переименовать метод на глагол без is.
И не забывайте проверять, что пришедший объект не null. Иначе NPE в первой же строке.

2022-08-19 15:00 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        isValid(film);
Валидация должна быть самой первой. Если film == null, то будет NPE.

2022-08-19 19:24 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        isValid(film);
Спасибо, исправил

2022-08-19 19:25 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void isValid(Film film) {
Исправил

2022-08-19 19:25 UTC, merged