feature: подключена база данных
TrapeznikovDanila/java-filmorate pull request #3
Opened 2022-09-19 16:14 UTC by TrapeznikovDanila

2022-09-20 11:50 UTC, sergeymamonov requested changes
Еще можно добавить единообразия, сейчас в каких-то пакетах и интерфейсы и классы лежат вместе, а в каких-то пакетах разложены по подпакетам.
Также
- в проекте должна быть картинка схемы бд
- в файле `README.md` должна быть ссылка на файл диаграммы.

2022-09-20 11:50 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmGenresDaoImpl.java
> +            jdbcTemplate.update(sqlQuery2,
Запросы в цикле к базе - не самая лучшая практика. Нужно стремиться, чтобы запрос в БД был один.

2022-09-20 11:50 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.setId(Long.valueOf(resultSet.getLong("film_id")));
Действительно нужно использовать Long.valueOf?
Есть использовать long в местах, где требуется Long, то происходит автоупаковка.

2022-09-20 13:51 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.setId(Long.valueOf(resultSet.getLong("film_id")));
Исправлено

2022-09-22 21:32 UTC, sergeymamonov approved these changes

2022-09-22 21:32 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmGenresDaoImpl.java
> +//        Set<Integer> sortedGenresList = new HashSet<>(genresList);
В проекте не должно быть закомментированного кода

2022-09-22 21:32 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmGenresDaoImpl.java
> +public class FilmGenresDaoImpl implements FilmGenreDao {
В названии класса множественное число для жанров, а в интерфейсе - единственное. Везде должно быть единообразно. Обратите внимание FriendsDao и GenreDao.

2022-09-22 21:32 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmGenresDaoImpl.java
> +                collect(Collectors.toSet()).
Обычно точку пишут перед методом, то есть начинают с нее строку, а не оставляют точку после предыдущего, то есть в конце строки.

2022-09-23 06:54 UTC, TrapeznikovDanila commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmGenresDaoImpl.java
> +            jdbcTemplate.update(sqlQuery2,
Исправлено

2022-09-23 07:20 UTC, merged